### ISSUE TITLE
Bad Request for path: /api/profiles

### ISSUE THREAD

**Issue by fekle** [MeltanoLabs/tap-klaviyo#13]
Hi there, I'm trying to use the `tap-klaviyo` plugin (`meltanolabs` variant), but i'm seeing some issues.

I want to extract all my lists and profiles form Klaviyo. Extracting Lists succeeds without error but does not extract anything, and extracting Profiles fails with the error `Bad Request for path: /api/profiles`.

Here is the relevant part from my Meltano Config:
```yaml
- name: tap-klaviyo
  config:
    revision: "2023-02-22"
    start_date: "2023-01-01"
  select:
    - lists.*
    - profiles.*
```

I already tried the following:
- creating a new Full Access API Token
- creating a new Read-Only Everything API Token (i prefer that over a full access token, as read-only should suffice for extraction)
- using older revisions (`1`, `2` or `2022-10-17`)
- omitting the `start_date` or using a different `start_date`
- requesting only specific profile attributes (eg `profiles.id`)
- using `replication-method: FULL_TABLE`

The same issue also occurs with the `events` endpoint.

What is curios is that it does extract 20 of about 25k profiles (or 200 events when selecting that) before failing, while it does not extract any lists (but no error for lists).

Am I doing something wrong here? Or does this tap simply not work anymore with the current Klaviyo api?

Please let me know if I can do anything to help :)

**Comment by fekle** [comment]
Amazing, thank you for the quick work! :)

I can confirm that it seems to work now - both with full table sync and without.

One small nitpick: There seems to be a small bug in the logger when handling the rate limit:

```
2023-05-22T20:21:17.042078Z [info     ] 2023-05-22 22:21:17,041 | INFO     | backoff              | Backing off _request(...) for 4.4s (singer_sdk.exceptions.RetriableAPIError: 429 Client Error: Too Many Requests for path: /api/profiles) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.042149Z [info     ] --- Logging error ---          cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.042257Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.042619Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.042865Z [info     ]     ret = target(*args, **kwargs) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043010Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/rest.py", line 274, in _request cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043146Z [info     ]     self.validate_response(response) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043276Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/rest.py", line 185, in validate_response cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043400Z [info     ]     raise RetriableAPIError(msg, response) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043523Z [info     ] singer_sdk.exceptions.RetriableAPIError: 429 Client Error: Too Many Requests for path: /api/profiles cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043650Z [info     ]                                cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043773Z [info     ] During handling of the above exception, another exception occurred: cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.043892Z [info     ]                                cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044014Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044131Z [info     ]   File "/REDACTED/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 1083, in emit cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044246Z [info     ]     msg = self.format(record)  cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044367Z [info     ]   File "/REDACTED/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 927, in format cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044483Z [info     ]     return fmt.format(record)  cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044597Z [info     ]   File "/REDACTED/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 663, in format cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044713Z [info     ]     record.message = record.getMessage() cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044829Z [info     ]   File "/REDACTED/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 367, in getMessage cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.044944Z [info     ]     msg = msg % self.args      cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045062Z [info     ] TypeError: format requires a mapping cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045176Z [info     ] Call stack:                    cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045295Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/bin/tap-klaviyo", line 8, in <module> cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045414Z [info     ]     sys.exit(TapKlaviyo.cli()) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045532Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__ cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045646Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045763Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045879Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.045995Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046112Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046228Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046345Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046460Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 533, in cli cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046574Z [info     ]     tap.sync_all()             cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046690Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/tap_base.py", line 423, in sync_all cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046802Z [info     ]     stream.sync()              cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.046918Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1187, in sync cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047031Z [info     ]     for _ in self._sync_records(context=context): cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047146Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/core.py", line 1086, in _sync_records cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047261Z [info     ]     for record_result in self.get_records(current_context): cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047376Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/rest.py", line 574, in get_records cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047490Z [info     ]     for record in self.request_records(context): cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047603Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/rest.py", line 395, in request_records cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047715Z [info     ]     resp = decorated_request(prepared_request, context) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.047827Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/backoff/_sync.py", line 124, in retry cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048369Z [info     ]     _call_handlers(on_backoff, **details, wait=seconds, cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048464Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/backoff/_sync.py", line 20, in _call_handlers cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048526Z [info     ]     hdlr(details)              cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048585Z [info     ]   File "/REDACTED/.meltano/extractors/tap-klaviyo/venv/lib/python3.9/site-packages/singer_sdk/streams/rest.py", line 660, in backoff_handler cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048643Z [info     ]     logging.error(             cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048696Z [info     ] Message: 'Backing off %(wait)0.2f seconds after %(tries)d tries calling function %(target)s with args %(args)s and kwargs %(kwargs)s' cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
2023-05-22T20:21:17.048749Z [info     ] Arguments: (4.352509878991215, 2, <bound method RESTStream._request of <tap_klaviyo.streams.ProfilesStream object at 0x105157850>>, (<PreparedRequest [GET]>, None), {}) cmd_type=elb consumer=False name=tap-klaviyo producer=True stdio=stderr string_id=tap-klaviyo
```

I'll open a pull request to fix this :)

**Comment by edgarrmondragon** [comment]
> I'll open a pull request to fix this :)

Thanks @fekle! That's likely a bug in the SDK: https://github.com/meltano/sdk/blob/afc5c67950890a5c1adceb84e6260d02a9ea183a/singer_sdk/streams/rest.py#L660-L669

**Comment by fekle** [comment]
Yes, I just realized the same, I'll open an Issue over there.

**Comment by edgarrmondragon** [comment]
I just noticed that I'm fixing that in https://github.com/meltano/sdk/pull/1686 😅
